services:
  consul:
    image: hashicorp/consul:1.16.1
    ports:
      - "8500:8500" 
    command: consul agent -server -bootstrap -ui -client=0.0.0.0 -data-dir=/consul/data
    volumes:
      - ./consul/data:/consul/data

  consul-template:
    image: hashicorp/consul-template:0.27.2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.template
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      CONSUL_HTTP_ADDR: consul:8500
    command: >
      consul-template -template "/etc/nginx/nginx.conf.template:/etc/nginx/nginx.conf:nginx -s reload"
    depends_on:
      - consul
      - nginx

  backend1:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python register_service.py && python main.py"
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db
      - consul
    environment:
      SERVICE_NAME: "client1"
      SERVICE_PORT: 5000
      SERVICE_HOST: "backend1"  # Nome do contêiner
      CONSUL_URL: "http://consul:8500"

  backend2:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python register_service.py && python main.py"
    ports:
      - 8002:5000
    volumes:
      - .:/app
    depends_on:
      - db
      - consul
    environment:
      SERVICE_NAME: "client2"
      SERVICE_PORT: 5000
      SERVICE_HOST: "backend2"  # Nome do contêiner
      CONSUL_URL: "http://consul:8500"

  backend3:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python register_service.py && python main.py"
    ports:
      - 8003:5000
    volumes:
      - .:/app
    depends_on:
      - db
      - consul
    environment:
      SERVICE_NAME: "client3"
      SERVICE_PORT: 5000
      SERVICE_HOST: "backend3"  # Nome do contêiner
      CONSUL_URL: "http://consul:8500"

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8004:80"
    depends_on:
      - backend1
      - backend2
      - backend3
      - queue
      - db