# Generated by Django 4.1 on 2024-10-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
