# Generated by Django 4.1 on 2024-11-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_avg_rating_product_num_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='num_ratings',
            new_name='ratings_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='avg_rating',
        ),
        migrations.AddField(
            model_name='product',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
